name: 'Git Push Action For Coding Page'
description: 'Git Push Action For Coding Page'
author: 'Anonystar <me@AnonyStar>'
inputs: 
  GITHUB_EMAIL:
    description: 'git user email'
    default: "AnonyStar"
  GITHUB_USERNAME:
    description: 'git use username'
    default: "me@AnonyStar.cn"
  PUBLISH_REPO:
    description: 'https:/<token>@github.com/owner/repo.git'
  PUBLISH_BRANCH:
    description: 'git branch'
  PUBLISH_DIR:
    description: 'dir to publish'
runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  color: "blue"
  icon: "code"
